# schemas/ecommerce/products.yml
products:
  rows: 200
  columns:
    id:
      type: "$faker"
      method: "uuid4"
      unique: True
      
    name:
      type: "$provider"
      target: "FurnitureFullNameProvider"
      bind_to: id
      
    price:
      type: "$provider"
      target: "FurniturePriceProvider"
      bind_to: name

    price_with_vat:
      type: "$func"
      func: "calculated.add_vat"
      params:
        value: $col(price)
        rate: 0.1

    stock_quantity:
      type: "$faker"
      method: "random_int"
      params:
        min: 10
        max: 500

    created_at:
      type: "$faker"
      method: "date_between"
      params:
        start_date: "-1y"
        end_date: "today"
    
    test:
      type: "$func"
      func: "test.country_of_origin"
      params:
        full_name: False
  output:
    format: csv
    filepath: "./outputs/products.csv"
