# schemas/products.yml
products:
  rows: 200
  columns:
    id:
      type: "$faker"
      method: "uuid4"
      unique: True
      
    name:
      type: "$provider"
      target: "FurnitureNameProvider"
      bind_to: id
      
    price:
      type: "$provider"
      target: "FurniturePriceProvider"
      bind_to: name

    stock_quantity:
      type: "$faker"
      method: "random_int"
      params:
        min: 10
        max: 500

    created_at:
      type: "$faker"
      method: "date_between"
      params:
        start_date: "-1y"
        end_date: "today"
  output:
    format: csv
    filepath: "./outputs/products.csv"
